title: FLkit
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

#topnav_title: FLKit
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Best practices and guidelines you can use when applying Federated Learning to your research"
# Metadata description of the website

# Names for common variables referenced in the pages
REPO: https://github.com/UHasselt-BiomedicalDataSciences/federated-learning-toolkit
WEBSITE: https://uhasselt-biomedicaldatasciences.github.io/federated-learning-toolkit
EMAIL: lotte.geys@uhasselt.be
# NOTE: code of conduct email (COC_EMAIL) is hardcoded in CODE_OF_CONDUCT.md (it needs to be changed there manually)
COC_EMAIL: lotte.geys@uhasselt.be

# For referencing to RDMkit
RDM_KIT_REPO: https://github.com/elixir-europe/rdmkit
RDM_KIT_WEBSITE: https://rdmkit.elixir-europe.org

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@3.2.0

sass:
  style: compressed
  sourcemap: never

exclude:
  - README.md
  - .gitignore
  - vendor
  - Gemfile*
  - LICENSE

defaults:
  # Define here page metadata attributes for all pages at once or on specific directories. More information: https://jekyllrb.com/docs/configuration/front-matter-defaults/
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/contribute"
    values:
      sidebar: contribute

theme_variables:
  dev-info-banner: true
  topnav:
    theme: dark
  theme_color: c23669
  fonts:
    - https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400&display=swap
    - https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap
  headings:
    resource-table-all-collapse: true

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - jekyll-octicons # used to render octicons in markdown files
  - jekyll-scholar  # used to cite papers in markdown files
  - webrick

# --- Missing in gitlab: ---
# github:
#   repository_url: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
#   source:
#     branch: main

